variables:
  IMAGE_TAG: $CI_PIPELINE_ID-$CI_COMMIT_REF_NAME

stages:
  - build
  - deploy

services:
- docker:dind

build:
  image: docker:latest
  stage: build
  script:
    - docker login registry.gitlab.com -u ${USERNAME} -p ${REGISTRY_PASSWORD}
    - docker build -t registry.gitlab.com/oleh_kuryshko/dtapi:${IMAGE_TAG} --build-arg DB_HOST=${DB_HOST} --build-arg DB_NAME=${DB_NAME} --build-arg DB_PASSWORD=${DB_PASSWORD} --build-arg DB_USER=${DB_USER} .
    - docker push registry.gitlab.com/oleh_kuryshko/dtapi:${IMAGE_TAG}
  tags:
    - docker

deploy:
  image: google/cloud-sdk:latest
  stage: deploy
  script:
    - sed -i "s/IMAGE_TAG/${IMAGE_TAG}/g" ci/svc-dp-bk.yml
    - echo ${GOOGLE_KEY} > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud container clusters get-credentials d-tester-claster --zone us-central1-f --project ${PROJECT_ID}
    - gcloud config set container/use_client_certificate True
    - kubectl apply -f ci/svc-dp-bk.yml
  when: manual
  tags:
    - docker
#test
