#backend
---
#service backend
apiVersion: v1
kind: Service
metadata:
  name: dtester-backend
  namespace: dtester
  labels:
    app: dtapi
    tier: backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dtapi
    tier: backend
  type: ClusterIP

---
#deployment backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtester-backend
  namespace: dtester
  labels:
    app: dtapi
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dtapi
      tier: backend
  template:
    metadata:
      labels:
        app: dtapi
        tier: backend
    spec:
      containers:
      - name: dtester-backend
        image: registry.gitlab.com/oleh_kuryshko/dtapi:IMAGE_TAG
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: dtester-backend
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80